# Generated by Django 4.2.26 on 2026-01-21 02:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('invite_code', models.CharField(default=accounts.models.generate_invite_code, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='simpleuser',
            name='create_at',
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='is_group_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='groups',
            field=models.ManyToManyField(blank=True, to='accounts.group'),
        ),
    ]
