# Generated by Django 5.2.8 on 2025-11-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpleuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
