# Generated by Django 5.2.8 on 2026-01-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_simpleuser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpleuser",
            name="is_group_leader",
            field=models.BooleanField(default=False),
        ),
    ]
