# Generated by Django 5.2.8 on 2026-01-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_simpleuser_is_group_leader"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("invite_code", models.CharField(max_length=10, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="simpleuser",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="simpleuser",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="simpleuser",
            name="groups",
            field=models.ManyToManyField(blank=True, to="accounts.group"),
        ),
    ]
