# Generated by Django 5.2.8 on 2026-01-16 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_group_alter_simpleuser_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simpleuser",
            name="create_at",
        ),
    ]
