# Generated by Django 5.2.8 on 2026-01-16 03:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_simpleuser_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="invite_code",
            field=models.CharField(
                default=accounts.models.generate_invite_code, max_length=6, unique=True
            ),
        ),
    ]
