# Generated by Django 4.2.26 on 2026-02-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_remove_simpleuser_create_at_and_more'),
        ('accounts', '0006_alter_group_invite_code'),
    ]

    operations = [
    ]
